name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Change this if your main branch is named differently

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20  # Use the latest stable Node.js version

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: dist  # Ensure this matches your Vite build output folder

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4